"""Second migration

Revision ID: d2532453659a
Revises: dbbf1e27c49d
Create Date: 2024-07-09 04:50:34.169119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2532453659a'
down_revision = 'dbbf1e27c49d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
